### ISSUE TITLE
华为mate30，小米8se，你的demo连图片都加载不出来

### ISSUE THREAD

**Issue by megvil** [hewuzhao/FrameAnimation#2]
demo连图片都加载不出来

**Comment by hewuzhao** [comment]
@yejiurui  我手上没有华为mate30和小米8se，请问一下，你这两个手机的Android版本是多少呢？

**Comment by hewuzhao** [comment]
@yejiurui  是由于Android高版本下使用了反射导致动画文件解析失败。最新版本已经修复。

**Comment by megvil** [comment]
666
